# Basic package information
set(CPACK_PACKAGE_VENDOR "Genci Berisha")
set(CPACK_PACKAGE_CONTACT "me@genciberisha.dev")
set(CPACK_PACKAGE_DESCRIPTION "Libzero - testing lib")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://github.com/neg-c/workflow_playground")
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")
set(CPACK_PACKAGE_DESCRIPTION_FILE "${CMAKE_CURRENT_SOURCE_DIR}/README.md")

# Version information from project
set(CPACK_PACKAGE_VERSION ${PROJECT_VERSION})
set(PACKAGE_ARCHITECTURE "amd64")

if(WIN32)
  set(CPACK_GENERATOR "NSIS64;ZIP")
  set(CPACK_PACKAGE_FILE_NAME "${PROJECT_NAME}-${PROJECT_VERSION}-win64-${PACKAGE_ARCHITECTURE}")
  
  # NSIS specific
  set(CPACK_NSIS_PACKAGE_NAME "${PROJECT_NAME}")
  set(CPACK_NSIS_DISPLAY_NAME "${PROJECT_NAME}")
  set(CPACK_NSIS_CONTACT "${CPACK_PACKAGE_CONTACT}")
  set(CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL ON)
  set(CPACK_NSIS_MODIFY_PATH ON)
  set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES64")
else()
  set(CPACK_GENERATOR "DEB;RPM;TGZ")
  set(CPACK_PACKAGE_FILE_NAME "${PROJECT_NAME}-${PROJECT_VERSION}-linux-${PACKAGE_ARCHITECTURE}")
  
  # DEB specific
  set(CPACK_DEBIAN_PACKAGE_SECTION "libs")
  set(CPACK_DEBIAN_PACKAGE_PRIORITY "optional")
  set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "${PACKAGE_ARCHITECTURE}")
  set(CPACK_DEBIAN_PACKAGE_DEPENDS "libc6 (>= 2.17)")
  
  # RPM specific
  set(CPACK_RPM_PACKAGE_LICENSE "MIT")
  set(CPACK_RPM_PACKAGE_GROUP "Development/Libraries")
  set(CPACK_RPM_PACKAGE_ARCHITECTURE "${PACKAGE_ARCHITECTURE}")
  set(CPACK_RPM_PACKAGE_REQUIRES "glibc >= 2.17")
  
  # Prevent RPM from generating debug/source packages
  set(CPACK_RPM_BUILD_SOURCE_DIRS_PREFIX "")
  set(CPACK_RPM_DEBUGINFO_PACKAGE OFF)
  set(CPACK_RPM_RELOCATION_PATHS "")
  
  # Force consistent naming for all package types
  set(CPACK_RPM_FILE_NAME "${CPACK_PACKAGE_FILE_NAME}.rpm")
  set(CPACK_DEBIAN_FILE_NAME "${CPACK_PACKAGE_FILE_NAME}.deb")
  set(CPACK_ARCHIVE_FILE_NAME "${CPACK_PACKAGE_FILE_NAME}")
endif()

include(CPack)
