name: cmake-format
on:
  pull_request_target:
    types: [opened]

jobs:
  cmake-format-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: neg-c/cmake-format-action@v0.1.2
        with:
          source: '.'
          exclude: 'third_party external'
          inplace: False
          style: file
